In [1]:
notas1 = [12, 7, 10, 11]
notas2 = [15, 14, 17, 13]

In [2]:
type(notas1)

list

In [5]:
suma = []

# len(notas1) = 4
# range(4) = [0, 1, 2, 3]
for i in range(len(notas1)):
  suma.append(notas1[i] + notas2[i])

print(suma)

[27, 21, 27, 24]


# Con Numpy

In [6]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [11]:
import numpy as np

In [12]:
notas3 = np.array([12, 7, 10, 11])
notas4 = np.array([15, 14, 17, 13])

In [13]:
type(notas3)

numpy.ndarray

In [14]:
notas3 + notas4

array([27, 21, 27, 24])

In [15]:
print(np.__version__)

1.22.4


## Dimensiones

In [18]:
arreglo = np.array([3, 5, 7])
print(arreglo)

[3 5 7]


In [19]:
arreglo.ndim

1

In [23]:
arreglo2d = np.array([[2, 4], [3, 5]])
print(arreglo2d)
print(type(arreglo2d))

[[2 4]
 [3 5]]
<class 'numpy.ndarray'>


In [22]:
test = [[2, 4], [3, 5]]
print(test)
print(type(test))

[[2, 4], [3, 5]]
<class 'list'>


In [24]:
arreglo2d.ndim

2

In [25]:
arreglo3d = np.array([[[2, 4], [3, 5]], [[6, 8], [7, 9]]])
print(arreglo3d)

[[[2 4]
  [3 5]]

 [[6 8]
  [7 9]]]


In [26]:
arreglo3d.ndim

3

In [27]:
arreglo2d = np.array([[2, 4], [3, 5]])
print(arreglo2d)

[[2 4]
 [3 5]]


In [28]:
arreglo2e = np.array([[1, 3], [2, 4]])
print(arreglo2e)

[[1 3]
 [2 4]]


In [30]:
sumaMatrices = arreglo2d + arreglo2e
print(sumaMatrices)

[[3 7]
 [5 9]]


In [31]:
print(type(sumaMatrices))

<class 'numpy.ndarray'>


In [32]:
sumaMatrices.ndim

2

## Accediendo a datos

In [35]:
arreglo = np.array([3, 5, 7, 9, 1, 12, 15])
print(arreglo)

[ 3  5  7  9  1 12 15]


In [36]:
arreglo[1]

5

In [37]:
arreglo[5]

12

In [38]:
arreglo[-2]

12

In [39]:
arreglo[-3]

1

In [41]:
# slicing
arreglo[1:4]

array([5, 7, 9])

In [42]:
#[ 3  5  7  9  1 12 15]
arreglo[2:6]

array([ 7,  9,  1, 12])

In [43]:
arreglo[2:-1]

array([ 7,  9,  1, 12])

In [44]:
arreglo[:-1]

array([ 3,  5,  7,  9,  1, 12])

In [45]:
arreglo[1:]

array([ 5,  7,  9,  1, 12, 15])

In [46]:
arreglo2d = np.array([[2, 4], [3, 5]])
print(arreglo2d)

[[2 4]
 [3 5]]


In [47]:
arreglo2d[0]

array([2, 4])

In [48]:
arreglo2d[0][1]

4

In [49]:
arreglo2d[1]

array([3, 5])

In [50]:
arreglo2d[1][0]

3

In [51]:
arregloX = np.array([[2, 4, 6, 8], [3, 5, 7, 9]])
print(arregloX)

[[2 4 6 8]
 [3 5 7 9]]


In [52]:
arregloX[1]

array([3, 5, 7, 9])

In [53]:
arregloX[1][2:]

array([7, 9])

In [54]:
arregloX.ndim

2

In [55]:
arregloX.shape

(2, 4)

In [56]:
arreglo2d.shape

(2, 2)

In [57]:
arreglo

array([ 3,  5,  7,  9,  1, 12, 15])

In [58]:
arreglo.ndim

1

In [59]:
arreglo.shape

(7,)

In [60]:
arreglo = np.array([3, 5, 7, 9, 1, 12, 15, 99])
print(arreglo)

[ 3  5  7  9  1 12 15 99]


In [61]:
arreglo.shape

(8,)

In [62]:
arreglo.reshape(2, 4)

array([[ 3,  5,  7,  9],
       [ 1, 12, 15, 99]])

In [63]:
arreglo.reshape(4, 2)

array([[ 3,  5],
       [ 7,  9],
       [ 1, 12],
       [15, 99]])

In [64]:
arreglo.reshape(2, -1)

array([[ 3,  5,  7,  9],
       [ 1, 12, 15, 99]])

In [65]:
arreglo.reshape(3, -1)

ValueError: ignored

In [66]:
arreglo

array([ 3,  5,  7,  9,  1, 12, 15, 99])

In [67]:
arreglo.shape

(8,)

In [72]:
tmp = arreglo.reshape(-1, 1)
tmp

array([[ 3],
       [ 5],
       [ 7],
       [ 9],
       [ 1],
       [12],
       [15],
       [99]])

In [73]:
tmp.shape

(8, 1)

In [71]:
arreglo.reshape(1, -1)

array([[ 3,  5,  7,  9,  1, 12, 15, 99]])

In [74]:
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])

In [76]:
arr1

array([1, 3, 5])

In [77]:
arr2

array([2, 4, 6])

In [78]:
arrRes = np.concatenate((arr1, arr2))
arrRes

array([1, 3, 5, 2, 4, 6])

In [79]:
type(arrRes)

numpy.ndarray

In [80]:
arrRes.shape

(6,)

In [83]:
arrRes = np.concatenate((arr1, arr2))
arrRes

array([1, 3, 5, 2, 4, 6])

In [84]:
np.hstack((arr1, arr2))

array([1, 3, 5, 2, 4, 6])

In [85]:
np.vstack((arr1, arr2))

array([[1, 3, 5],
       [2, 4, 6]])

In [86]:
arrRes

array([1, 3, 5, 2, 4, 6])

In [87]:
np.where(arrRes > 3)

(array([2, 4, 5]),)

In [89]:
out = np.where(arrRes%2 == 0)
out

(array([3, 4, 5]),)

In [91]:
for i in out[0]:
  print(arrRes[i])

2
4
6


In [92]:
for i in np.where(arrRes%2 == 0)[0]:
  print(arrRes[i])

2
4
6


In [93]:
np.sort(arrRes)

array([1, 2, 3, 4, 5, 6])

In [94]:
arrRes

array([1, 3, 5, 2, 4, 6])

In [95]:
arrRes > 2

array([False,  True,  True, False,  True,  True])

In [96]:
arrRes[arrRes > 2]

array([3, 5, 4, 6])

In [97]:
arrRes[arrRes%2 != 0]

array([1, 3, 5])

In [98]:
arrRes[arrRes%4 != 0]

array([1, 3, 5, 2, 6])